---
title: "Results of the single step benchmark"
author: "Léopold Guyot"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages}
library(tidyverse)
library(benchmarkme)
library(plotly)
library(DT)
```

```{r dataloading}
inputDir <- "dataOutput/individualStepsBenchmark"
files <- list.files(path = inputDir, full.names = TRUE)
fileSizeReport <- "dataOutput/individualStepsBenchmark/qfeatures_size_report.tsv"
stepResults <- files[!files == fileSizeReport]

stepDataList <- lapply(stepResults, function(x) {
    l <- as.list(read.csv(x)[1, 3:5])
    l$name <- sub(".csv", "", basename(x))
    l
})

sizeTable <- read.table(fileSizeReport, header = TRUE)

peakRamTable <- do.call(rbind, lapply(stepDataList, as.data.frame))
peakRamTable <- separate(peakRamTable, name, into = c("nCell", "step", "replicate"), sep = "_")
```

# Heatmap of time elapsed by number of cells and steps

```{r heatmapTime}
nCell_order <- c("500", "1000", "2000", "4000")
step_order <- c(
    "benchmarkFilterFeatures",
    "benchmarkFilterSamples",
    "benchmarkZeroisNA",
    "benchmarkAggPSM",
    "benchmarkJoinPSM",
    "benchmarkNormSampPep",
    "benchmarkNormFeatPep",
    "benchmarkLogPep",
    "benchmarkAggPep",
    "benchmarkImputePro"
)

timeMedian <- peakRamTable %>%
    group_by(nCell, step) %>%
    summarise(medianTimeElasped = median(Elapsed_Time_sec)) %>%
    ungroup() %>%
    mutate(
        nCell = factor(nCell, levels = nCell_order),
        step = factor(step, levels = rev(step_order))
    )


ggplotly(ggplot(timeMedian, aes(nCell, step, fill = medianTimeElasped)) +
    geom_tile() +
    scale_fill_gradient2(
        low = "blue", mid = "white", high = "red",
        midpoint = median(peakRamTable$Elapsed_Time_sec, na.rm = TRUE)
    ))

ggplotly(ggplot(timeMedian, aes(nCell, step, fill = medianTimeElasped)) +
    geom_tile() +
    scale_fill_gradient2(
        low = "blue", mid = "white", high = "red",
        midpoint = median(peakRamTable$Elapsed_Time_sec, na.rm = TRUE),
        transform = "log2"
    ))
DT::datatable(timeMedian)
```

# Heatmap of peak RAM by number of cells and steps

```{r heatmapPeakRam}
convert_mib_to_gb <- function(mib) {
    gb <- mib * 0.001024
    return(gb)
}
peakRamMedian <- peakRamTable %>%
    group_by(nCell, step) %>%
    summarise(medianPeakRam = median(Peak_RAM_Used_MiB)) %>%
    ungroup() %>%
    mutate(
        nCell = factor(nCell, levels = nCell_order),
        step = factor(step, levels = rev(step_order))
    )
ggplotly(ggplot(peakRamMedian, aes(nCell, step, fill = medianPeakRam)) +
    geom_tile() +
    scale_fill_gradient2(
        low = "blue", mid = "white", high = "red",
        midpoint = median(peakRamTable$Peak_RAM_Used_MiB, na.rm = TRUE)
    ))

ggplotly(ggplot(peakRamMedian, aes(nCell, step, fill = medianPeakRam)) +
    geom_tile() +
    scale_fill_gradient2(
        low = "blue", mid = "white", high = "red",
        midpoint = median(peakRamTable$Peak_RAM_Used_MiB, na.rm = TRUE),
        transform = "log2"
    ))
DT::datatable(peakRamMedian)
```

# Difference in global size for each step

```{r heatmapSize}
convert_bytes_to_mib <- function(bytes) {
    mib <- bytes / (2^20)
    return(mib)
}

sizeDiff <- sizeTable %>%
    group_by(nCell, step) %>%
    summarise(
        medianSizeBefore = median(sizeTotalBefore),
        medianSizeAfter = median(sizeTotalAfter)
    ) %>%
    mutate(medianSizeDiffMiB = convert_bytes_to_mib(medianSizeAfter - medianSizeBefore)) %>%
    ungroup() %>%
    mutate(
        nCell = factor(nCell, levels = nCell_order),
        step = factor(step, levels = rev(step_order))
    )

ggplotly(ggplot(sizeDiff, aes(nCell, step, fill = medianSizeDiffMiB)) +
    geom_tile() +
    scale_fill_gradient2(low = "blue", mid = "white", high = "red"))
DT::datatable(sizeDiff)
```

```{r heatmapComponentSize}
convert_bytes_to_mib <- function(bytes) {
    mib <- bytes / (2^20)
    return(mib)
}

sizeComponentDiff <- sizeTable %>%
    filter(nCell == 4000) %>%
    group_by(step) %>%
    summarise(
        medianDiffAssay = convert_bytes_to_mib(median(sizeAssayAfter - sizeAssayBefore)),
        medianDiffRowData = convert_bytes_to_mib(median(sizeRowDataAfter - sizeRowDataBefore)),
        medianDiffColData = convert_bytes_to_mib(median(sizeColDataAfter - sizeColDataBefore))
    ) %>%
    ungroup() %>%
    pivot_longer(
        cols = c(medianDiffAssay, medianDiffRowData, medianDiffColData),
        names_to = "component", values_to = "medianSizeMiB"
    ) %>%
    mutate(step = factor(step, levels = rev(step_order)))

ggplotly(ggplot(sizeComponentDiff, aes(component, step, fill = medianSizeMiB)) +
    geom_tile() +
    scale_fill_gradient2(low = "blue", mid = "white", high = "red"))

DT::datatable(sizeComponentDiff)
```

# Variation in run time by step

```{r}
peakRamTableOrdered <- peakRamTable %>%
    mutate(
        step = factor(step, levels = rev(step_order)),
        nCell = as.integer(nCell)
    ) %>%
    group_by(nCell, step) %>%
    summarise("medianTimeSec" = median(Elapsed_Time_sec))

ggplotly(ggplot(peakRamTableOrdered, aes(x = nCell, y = medianTimeSec)) +
    geom_line() +
    facet_wrap(~step))
```

